config:
  exposedMethods:
    AddCredentials: GoogleNowService::addCredentials
    CheckCredentials: GoogleNowService::checkCredentials
  thriftFile: clients/googlenow/googlenow.thrift
  thriftFileSha: '{{placeholder}}'
name: google-now
type: http
