clients:
  bar:
    ip: 127.0.0.1
    defaultHeaders:
      X-Client-ID: bar
    port: 4001
    timeout: 10000
  baz:
    ip: 127.0.0.1
    port: 4002
    serviceName: Qux
    timeout: 10000
    timeoutPerAttempt: 2000
  contacts:
    ip: 127.0.0.1
    port: 4000
    timeout: 10000
  corge:
    serviceName: Corge
    timeout: 10000
    timeoutPerAttempt: 2000
  google-now:
    ip: 127.0.0.1
    port: 14120
    timeout: 10000
  googleNowTChannel:
    connectionType: p2p
    hostList:
    - 127.0.0.1:4002
    timeout: 10000
  multi:
    ip: 127.0.0.1
    port: 4003
    timeout: 10000
envVarsToTagInRootScope: []
http:
  port: 0
logger:
  fileName: /tmp/example-gateway.log
  output: disk
metrics:
  type: m3
  serviceName: example-gateway
  m3:
    hostPort: 127.0.0.1:8888
env: development
service.env.config: {}
serviceName: example-gateway
shutdown.pollInterval: 10
sidecarRouter:
  default:
    http:
      calleeHeader: RPC-Service
      callerHeader: RPC-Caller
      ip: 127.0.0.1
      port: 4999
    tchannel:
      ip: 127.0.0.1
      port: 5000
tchannel:
  port: 0
  processName: example-gateway
  serviceName: example-gateway
useDatacenter: false
subLoggerLevel:
  jaeger: info
  http: info
  tchannel: info

